fos_rest:
    param_fetcher_listener: true
    disable_csrf_role: ROLE_API
    routing_loader:
        #default_format: json
        include_format: false
    serializer:
        serialize_null: true
    view:
        view_response_listener: 'force'
        #formats:
        #    json: true
        #    xml: true
        #    html: false
        #templating_formats:
        #    html: false
        #    json: true
    exception:
        enabled: true
        messages:
            Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true


nelmio_cors:
    paths:
        '^/api':
            origin_regex: true
            #allow_origin: ['^http://localhost:[0-9]+']
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            #allow_headers: ['X-Requested-With', 'Content-Type', 'Access-Control-Allow-Origin', 'Access-Control-Allow-Credentials', 'Access-Control-Allow-Headers']
            allow_headers: ['*']
            max_age: 3600